name: Deploy HTML files to GitHub Pages

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
    paths:
      - "*.html"
      - "script/*.ps1"   # Trigger when PowerShell scripts in script/ change


jobs:
  deploy-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-ps1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload PS1 files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./script/*.ps1

      - name: Deploy PS1 files to GitHub Pages
        id: deployment_ps1
        uses: actions/deploy-pages@v4
