name: Scheduled Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '6 22 3 8 0'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Deploy Script
        shell: pwsh
        run: |
          ./scripts/deploy.ps1 -RepoName "GitHubPages"
